### ISSUE TITLE
DNS64 can NOT work now,what can i do?

### ISSUE THREAD

**Issue by freessrnet3vnet** [YG-tsj/EUserv-addv4-warp#1]

**Comment by YG-tsj** [comment]
I think your server name has become DIG9. At present, a common phenomenon exists in individual accounts. After entering SSH, you will find root@DIG9. At this time, the server cannot connect to the external network and cannot download anything, which is unfortunate. Cannot be resolved at this time.

**Comment by YG-tsj** [comment]
> _没有提供描述。_

The new plan has been updated, please use it
