### ISSUE TITLE
新方法还是不行

### ISSUE THREAD

**Issue by le332313** [YG-tsj/EUserv-addv4-warp#2]
![image](https://user-images.githubusercontent.com/70869130/112797537-1cf54280-909e-11eb-8239-599be8f68d50.png)
试过几次了，系统也装过两次了，还是不行，这个怎么解决呀

**Comment by YG-tsj** [comment]
DIG9的话，把三个文件放在ROOT目录下进行安装。。不要用之前脚本，

**Comment by le332313** [comment]
chmod +x EUdig9.sh && ./EUdig9.sh
就是用这个脚本

**Comment by le332313** [comment]
文件也是都拷贝在ROOT目录了

**Comment by YG-tsj** [comment]
别改dns64！只用官方的

**Comment by le332313** [comment]
重装之后，没动过任何东西，直接拷贝文件，然后运行这个脚本。。

**Comment by YG-tsj** [comment]
这样。。你进入ROOT目录后，把EUdig9.sh文件全部删除。重装上传我这个新的，再运行，应该就没问题了。

**Comment by le332313** [comment]
新的可以，然后用不了你的意见脚本安装服务器。。。

**Comment by YG-tsj** [comment]
> 新的可以，然后用不了你的意见脚本安装服务器。。。

   哪个？？

**Comment by le332313** [comment]
wget https://raw.githubusercontent.com/YG-tsj/EUserv-addv4-warp/main/ub20db10.sh && chmod +x ub20db10.sh && ./ub20db10.sh
![image](https://user-images.githubusercontent.com/70869130/112925922-4026fd00-9145-11eb-98ed-da3b736bd502.png)

**Comment by le332313** [comment]
一直都会转到这个界面

**Comment by YG-tsj** [comment]
> 一直都会变成这个界面

你这个已经成功了呀。。安装代理脚本吧。

**Comment by le332313** [comment]
我就是安装代理脚本的，wget https://raw.githubusercontent.com/YG-tsj/EUserv-addv4-warp/main/ub20db10.sh && chmod +x ub20db10.sh && ./ub20db10.sh

没有进入你视频里面的界面

**Comment by YG-tsj** [comment]
晕。。这个是添加WARP脚本，装完就装A大或者 P大的脚本 吧。
