### ISSUE TITLE
找不到那个两个文件

### ISSUE THREAD

**Issue by GhostHjh** [YG-tsj/EUserv-addv4-warp#4]
无法在root目录下找到 **wgcf-profile.conf** 和 **wgcf-account.toml**
![image](https://user-images.githubusercontent.com/56105932/114296864-16c08680-9ae0-11eb-9721-fcc09ea03300.png)

**Comment by YG-tsj** [comment]
已更新脚本，现在两文件都放在/etc/wireguard下
